# Generated by Django 5.0 on 2025-10-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_petition'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
