# Generated by Django 5.0 on 2025-10-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_petition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='name',
        ),
    ]
